/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package g4s21p12jrlr2v;

import G4S21P12JRLR.Archivos;
import G4S21P12JRLR.DATOS;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author manny
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    DefaultTableModel modelotabla = new DefaultTableModel();
    List<DATOS> Datos = new ArrayList<>();
    int posicion = 0 ; 
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        TitulosTabla();
        Cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtedad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcorr = new javax.swing.JTextField();
        btnG = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DATOSAGRUPADOS = new javax.swing.JTable();

        tbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbdatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdatos);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Edad:");

        txtnom.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        txtedad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("Correo:");

        txtcorr.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtcorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorrActionPerformed(evt);
            }
        });

        btnG.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnG.setText("Grabar");
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });

        btnA.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnA.setText("Actualizar");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnE.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnE.setText("Eliminar");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnL.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnL.setText("Limpiar");
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });

        DATOSAGRUPADOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        DATOSAGRUPADOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DATOSAGRUPADOSMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DATOSAGRUPADOS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnom))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnG, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnA, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcorr)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcorr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnG)
                    .addComponent(btnA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnE)
                    .addComponent(btnL))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cargar(){
        Archivos conexion = new Archivos();
        if(conexion.VerificaArch()){
            if(conexion.Leer()){
                Datos = conexion.getDatos();
               // tbdatos.removeAll();
                CargarRegistrosTabla();
            }else{
                JOptionPane.showMessageDialog(this,
                        "No se puede leer la informacion",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"No existe el archivo, ingrese información",
                    "no existe", 
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }
    private void TitulosTabla(){
        modelotabla.addColumn("Nombre");
        modelotabla.addColumn("Edad");
        modelotabla.addColumn("Correo");
        DATOSAGRUPADOS.setModel(modelotabla);    
    }
    private void CargarRegistrosTabla(){
        Object[] filatabla = new Object[3];
        for(DATOS dato : Datos){
            filatabla[0]=dato.getNombre();
            filatabla[1]=dato.getEdad();
            filatabla[2]=dato.getCorreo();
            modelotabla.addRow(filatabla);
        }
        DATOSAGRUPADOS.setModel(modelotabla);
    }
    
    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        // TODO add your handling code here:
        Archivos conexion = new Archivos();
        DATOS dato = new DATOS();
        dato.setNombre(txtnom.getText().toString());
        dato.setEdad(txtedad.getText().toString());
        dato.setCorreo(txtcorr.getText().toString());

        conexion.Agregar(dato);
        Datos = conexion.getDatos();

        if(conexion.Grabar(Datos, 0 )){
            modelotabla = (DefaultTableModel) DATOSAGRUPADOS.getModel();
            modelotabla.getDataVector().removeAllElements();
            JOptionPane.showMessageDialog(this,
                "Se grabo correctamente",
                "Grabado",
                JOptionPane.INFORMATION_MESSAGE);
            Cargar();
            //CargarRegistrosTabla();
        }else{
            JOptionPane.showMessageDialog(this,
                "Error al grabar la informacion",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
        Archivos conexion = new Archivos();
        DATOS dato = new DATOS();
        dato.setNombre(txtnom.getText().toString());
        dato.setEdad(txtedad.getText().toString());
        dato.setCorreo(txtcorr.getText().toString());

        Datos.set(posicion, dato);
        if(conexion.Grabar(Datos, 1)){
            modelotabla = (DefaultTableModel) tbdatos.getModel();
            modelotabla.getDataVector().removeAllElements();
            JOptionPane.showMessageDialog(this,
                "Se actualizo correctamente",
                "Actualizado",
                JOptionPane.INFORMATION_MESSAGE);
            Cargar();
            //CargarRegistrosTabla();
        }else{
            JOptionPane.showMessageDialog(this,
                "Error al actualizar la informacion",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // TODO add your handling code here:
        Archivos conexion = new Archivos();
        /*Atributos dato = new Atributos();
        dato.setNombre(txtnombre.getText().toString());
        dato.setEdad(txtedad.getText().toString());
        dato.setSexo(txtsexo.getText().toString());*/

        Datos.remove(posicion);
        if(conexion.Grabar(Datos, 1)){
            modelotabla = (DefaultTableModel) DATOSAGRUPADOS.getModel();
            modelotabla.getDataVector().removeAllElements();
            JOptionPane.showMessageDialog(this,
                "Se elimino correctamente",
                "Eliminación",
                JOptionPane.INFORMATION_MESSAGE);
            Cargar();
            //CargarRegistrosTabla();
        }else{
            JOptionPane.showMessageDialog(this,
                "Error al eliminar la informacion",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEActionPerformed

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        // TODO add your handling code here:
        txtnom.setText("");
        txtedad.setText("");
        txtcorr.setText("");
    }//GEN-LAST:event_btnLActionPerformed

    private void tbdatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdatosMouseClicked
        // TODO add your handling code here:
        int nfilas = tbdatos.getSelectedRowCount();
        int fila = 0;
        if(nfilas == 1){
            fila = tbdatos.getSelectedRow();
            posicion = fila;
            txtnom.setText(tbdatos.getValueAt(fila, 0).toString());
            txtedad.setText(tbdatos.getValueAt(fila, 1).toString());
            txtcorr.setText(tbdatos.getValueAt(fila, 2).toString());
        }

    }//GEN-LAST:event_tbdatosMouseClicked

    private void DATOSAGRUPADOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DATOSAGRUPADOSMouseClicked
        // TODO add your handling code here:
        int nfilas = DATOSAGRUPADOS.getSelectedRowCount();
        int fila = 0;
        if(nfilas == 1){
            fila = DATOSAGRUPADOS.getSelectedRow();
            posicion = fila;
            txtnom.setText(DATOSAGRUPADOS.getValueAt(fila, 0).toString());
            txtedad.setText(DATOSAGRUPADOS.getValueAt(fila, 1).toString());
            txtcorr.setText(DATOSAGRUPADOS.getValueAt(fila, 2).toString());
        }
    }//GEN-LAST:event_DATOSAGRUPADOSMouseClicked

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void txtcorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DATOSAGRUPADOS;
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbdatos;
    private javax.swing.JTextField txtcorr;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
