/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package g4s21jrlrp4;

import java.awt.PopupMenu;

/**
 *
 * @author jrlr5
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private PopupMenu FrmSuma;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dbcontenido = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        intsuma = new javax.swing.JMenu();
        itmsuma = new javax.swing.JMenuItem();
        itmresta = new javax.swing.JMenuItem();
        itmmult = new javax.swing.JMenuItem();
        itemdivi = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dbcontenido.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout dbcontenidoLayout = new javax.swing.GroupLayout(dbcontenido);
        dbcontenido.setLayout(dbcontenidoLayout);
        dbcontenidoLayout.setHorizontalGroup(
            dbcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        dbcontenidoLayout.setVerticalGroup(
            dbcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        intsuma.setText("Operaciones");
        intsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intsumaActionPerformed(evt);
            }
        });

        itmsuma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmsuma.setText("Suma");
        itmsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmsumaActionPerformed(evt);
            }
        });
        intsuma.add(itmsuma);

        itmresta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmresta.setText("Resta");
        itmresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmrestaActionPerformed(evt);
            }
        });
        intsuma.add(itmresta);

        itmmult.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmmult.setText("Multiplicacion");
        itmmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmmultActionPerformed(evt);
            }
        });
        intsuma.add(itmmult);

        itemdivi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemdivi.setText("Divicion");
        itemdivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemdiviActionPerformed(evt);
            }
        });
        intsuma.add(itemdivi);

        jMenuBar1.add(intsuma);

        jMenu2.setText("Acerca de ");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Informacion");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dbcontenido)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dbcontenido)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmmultActionPerformed
         FrmMult frmmult = new FrmMult();
            frmmult.setVisible(true);
            dbcontenido.add(frmmult);// TODO add your handling code here:
    }//GEN-LAST:event_itmmultActionPerformed

    private void itemdiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemdiviActionPerformed
         FrmDivi frmdivi = new FrmDivi();
            frmdivi.setVisible(true);
            dbcontenido.add(frmdivi);// TODO add your handling code here:
    }//GEN-LAST:event_itemdiviActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void itmsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmsumaActionPerformed
        FrmSuma frmsuma = new FrmSuma();
            frmsuma.setVisible(true);
            dbcontenido.add(frmsuma);
        // TODO add your handling code here:
    }//GEN-LAST:event_itmsumaActionPerformed

    private void itmrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmrestaActionPerformed
        FrmResta frmresta = new FrmResta();
            frmresta.setVisible(true);
            dbcontenido.add(frmresta); // TODO add your handling code here:
    }//GEN-LAST:event_itmrestaActionPerformed

    private void intsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intsumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intsumaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dbcontenido;
    private javax.swing.JMenu intsuma;
    private javax.swing.JMenuItem itemdivi;
    private javax.swing.JMenuItem itmmult;
    private javax.swing.JMenuItem itmresta;
    private javax.swing.JMenuItem itmsuma;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
